global:
  scrape_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'spring-boot-app'
    static_configs:
      - targets: ['35.205.135.126:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s