- hosts: springboot
  become: true
  tasks:
    - name: Installer Java, Git et maven
      apt:
        name: [openjdk-21-jdk, git, maven]
        state: present
        update_cache: yes

    - name: Set JAVA_HOME environment variable
      become: yes
      lineinfile:
        path: /etc/environment
        regexp: '^JAVA_HOME='
        line: 'JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64'
        state: present

    - name: Cloner ou mettre à jour l'API
      git:
        repo: 'https://github.com/sachabarbet/gcp_ynov_api.git'
        dest: /home/sacha/apisrc
        version: main

    - name: Builder l'application
      shell: mvn -f /home/sacha/apisrc/api/pom.xml clean package -DskipTests

    - name: Find the JAR file
      ansible.builtin.find:
        paths: /home/sacha/apisrc/api/target/
        patterns: '*.jar'
      register: jar_files

    - name: Create app dir
      shell: mkdir ~/app

    - name: Copy the JAR file
      ansible.builtin.copy:
        src: "{{ item.path }}"
        dest: /home/sacha/app/app.jar
        remote_src: yes
      loop: "{{ jar_files.files }}"
      
    - name: Déployer le service systemd
      copy:
        dest: /etc/systemd/system/springboot.service
        content: |
          [Unit]
          Description=Spring Boot App
          After=network.target

          [Service]
          User=ubuntu
          ExecStart=/usr/bin/java -jar /home/sacha/app/app.jar
          Restart=always

          [Install]
          WantedBy=multi-user.target
      notify: Restart SpringBoot

  handlers:
    - name: Restart SpringBoot
      systemd:
        name: springboot
        state: restarted
        enabled: true