name: Release & Deploy

# Déclencheurs : tests à chaque commit/PR sur main, release manuelle ou sur tag
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  create:
    tags:
      - 'v*.*.*'

# Permissions globales
permissions:
  contents: write      # pour pouvoir push des tags & créer des releases
  id-token: write      # si vous utilisez OIDC
  actions: read

jobs:
  release-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Run release script
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
        run: |
          chmod +x release.sh
          ./release.sh
        
      - name: Authenticate GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Provision infra (Terraform)
        run: |
          cd infra
          terraform init
          terraform apply -auto-approve -var project_id=${{ secrets.GCP_PROJECT }}

      - name: Deploy Ansible
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/deploy.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'False'
