name: Release & Deploy

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run release script
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
        run: |
          chmod +x release.sh
          ./release.sh
        
      - name: Authenticate GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Provision infra (Terraform)
        run: |
          cd infra
          terraform init
          terraform apply -auto-approve

      - name: Deploy Ansible
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/deploy.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'False'
